// try {
//     let x=0;
//     console.log(x[1])
// } catch (error) {
//     console.log('error handling in catc',err)
    
// }finally{
//     console.log('finally always gets excuted')
// }

